run:
  tests: true

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - gofmt
    - testpackage
    - unconvert
    - whitespace

linters-settings:
  errcheck:
    exclude-functions:
      - github.com/spf13/viper.BindPFlag
  gofmt:
    simplify: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0