name: Go

on: [push, pull_request]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install actual-web
        run: npm install --no-dev

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install actual-web
        run: npm install --no-dev

      - name: Test
        run: go test -v ./...

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install actual-web
        run: npm install --no-dev

      - name: Build using GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: build --rm-dist --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
