name: Go

on: [ push, pull_request ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.1.1
      with:
        node-version-file: .nvmrc
        cache: npm
        cache-dependency-path: package-lock.json
        
    - name: Install
      run: npm install --no-dev

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
